# SPDX-License-Identifier: GPL-2.0

capability-analysis-cflags := -DWARN_CAPABILITY_ANALYSIS	\
	-fexperimental-late-parse-attributes -Wthread-safety	\
	$(call cc-option,-Wthread-safety-pointer)

ifndef CONFIG_WARN_CAPABILITY_ANALYSIS_ALL
capability-analysis-cflags += --warning-suppression-mappings=$(srctree)/scripts/capability-analysis-suppression.txt
endif

export CFLAGS_CAPABILITY_ANALYSIS := $(capability-analysis-cflags)
